// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okowpojqlredwewbenzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rb3dwb2pxbHJlZHdld2JlbnpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NzYyMTIsImV4cCI6MjA2MDM1MjIxMn0.psDXOLYLjytp9FhXdW7BNjVijh-qe9SmPaT45-ohF5s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);